# Generated by Django 5.1.1 on 2024-11-13 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachmentapplication',
            name='student_cv',
            field=models.FileField(upload_to='documents'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(upload_to='profile_images/'),
        ),
    ]
